POST http://localhost:3000/api/worksheet/get-active-worksheets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "userId": 5,
    "tankTypeId": 0,
    "statusId": 3
}

POST http://localhost:3000/api/worksheet/create-worksheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "ph": 7,
    "salnity": 35,
    "temperature": 32,
    "tankTypeId": 2,
    "tanks": [7],
    "harvestTypeId": 1,
    "harvestHours": 18,
    "inputCount": 20,
    "inputUnitId": 6,
    "statusId": 2,
    "userId": 1
}

POST http://localhost:3000/api/worksheet/create-worksheets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "ph": 7,
    "salnity": 35,
    "temperature": 32,
    "tankTypeId": 2,
    "tanks": [8,9],
    "harvestTypeId": 1,
    "harvestHours": 18,
    "inputCount": 20,
    "inputUnitId": 6,
    "statusId": 2,
    "userId": 1
}
// {
//   "worksheets": [{
//     "ph": 6,
//     "salnity": 10,
//     "temperature": 30,
//     "tankTypeId": 2,
//     "tankNumber": 3,
//     "harvestTypeId": 1,
//     "harvestHours": 18,
//     "inputUnitId": 1,
//     "inputCount": 12,
//     "statusId": 1,
//     "userId": 3
// }, {
//     "ph": 6,
//     "salnity": 11,
//     "temperature": 28,
//     "tankTypeId": 2,
//     "tankNumber": 4,
//     "harvestTypeId": 2,
//     "harvestHours": 18,
//     "inputUnitId": 6,
//     "inputCount": 5,
//     "statusId": 1,
//     "userId": 3
// }]
// }


POST http://localhost:3000/api/worksheet/create-harvest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
   "worksheetId": 13,
    "count": 30,
    "unitId": 2, // 1 - Tins, 2- Frozen Cups, 3 - Millions
    "measuredBy": 1,
    "restockCount": 10,
    "restockUnitId": 3,
    "statusId": 4
}

POST http://localhost:3000/api/worksheet/create-multiple-harvest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
  "harvests": [{
    "worksheetId": 13,
    "count": 50,
    "countInStock": 50,
    "unitId": 1,
    "measuredBy": 1,
    "restockCount": 10,
    "restockUnitId": 3,
    "statusId": 4
  }]
}



POST http://localhost:3000/api/worksheet/create-multiple-transit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
  "transits": [{
    "harvestId": 6,
    "unitSectorId": 1,
    "count": 20,
    "unitId": 1
  }]
}