POST http://localhost:3000/api/worksheet/create-worksheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "ph": 7,
    "salnity": 35,
    "temperature": 32,
    "tankTypeId": 1,
    "tankNumber": 21,
    "harvestTypeId": 1,
    "harvestTime": "2025-08-18T17:34:02.666Z",
    "inputSource": "bags",
    "inputCount": 20,
    "sourceUnitName": "kgs",
    "statusId": 2,
    "userId": 1
}

POST http://localhost:3000/api/worksheet/create-worksheets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
  "worksheets": [{
    "ph": 8,
    "salnity": 10,
    "temperature": 30,
    "tankTypeId": 2,
    "tankNumber": 17,
    "harvestTypeId": 2,
    "harvestTime": "2025-08-18T17:34:02.666Z",
    "inputSource": "tins",
    "inputCount": 12,
    "sourceUnitName": "",
    "statusId": 1,
    "userId": 3
}, {
    "ph": 8,
    "salnity": 10,
    "temperature": 30,
    "tankTypeId": 2,
    "tankNumber": 18,
    "harvestTypeId": 2,
    "harvestTime": "2025-08-18T17:34:02.666Z",
    "inputSource": "tins",
    "inputCount": 10,
    "sourceUnitName": "",
    "statusId": 1,
    "userId": 3
}]
}


POST http://localhost:3000/api/worksheet/create-harvest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    // "worksheetId": 1,
    // "tinsCount": 0,
    // "frozenCupsCount": 12,
    // "measuredBy": 1,
    // "restockCount": 10,
    // "restockUnit": "Millions"
    "worksheetId": 3,
    "tinsCount": 0,
    "frozenCupsCount": 30,
    "measuredBy": 1,
    "restockCount": 10,
    "restockUnit": "millions",
    "statusId": 4
}