PATCH http://localhost:3000/api/worksheet/update-worksheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "statusId": 3,
    "id": 8
}


PATCH http://localhost:3000/api/worksheet/update-worksheets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
//    "worksheets": [{
//         "userId": 1,
//         "id": 21
//     }, {
//         "userId": 1,
//         "id": 22
//     }],
//     "updateAction": "WORKSHEET_ASSIGNEE_UPDATED"
    
    "worksheets": [{
        "statusId": 2,
        "id": 21
    }, {
        "statusId": 2,
        "id": 22
    }],
    "updateAction": "WORKSHEET_STATUS_UPDATED"
}



