POST http://localhost:3000/api/worksheet/get-active-worksheets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "userId": 5,
    "tankTypeId": 0,
    "statusId": 3
}

POST http://localhost:3000/api/worksheet/create-worksheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "ph": 7,
    "salnity": 35,
    "temperature": 32,
    "tankTypeId": 2,
    "tanks": [7],
    "harvestTypeId": 1,
    "harvestHours": 18,
    "inputCount": 20,
    "inputUnitId": 6,
    "statusId": 2,
    "userId": 1
}

POST http://localhost:3000/api/worksheet/create-worksheets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "ph": 7.7,
    "salnity": 35,
    "temperature": 32,
    "tankTypeId": 1,
    "tanks": [3],
    "harvestTypeId": 1,
    "harvestHours": 18,
    "inputCount": 20,
    "inputUnitId": 6,
    "statusId": 2,
    "userId": 3,
    "restocks": [6, 4]

}
// {
//   "worksheets": [{
//     "ph": 6,
//     "salnity": 10,
//     "temperature": 30,
//     "tankTypeId": 2,
//     "tankNumber": 3,
//     "harvestTypeId": 1,
//     "harvestHours": 18,
//     "inputUnitId": 1,
//     "inputCount": 12,
//     "statusId": 1,
//     "userId": 3
// }, {
//     "ph": 6,
//     "salnity": 11,
//     "temperature": 28,
//     "tankTypeId": 2,
//     "tankNumber": 4,
//     "harvestTypeId": 2,
//     "harvestHours": 18,
//     "inputUnitId": 6,
//     "inputCount": 5,
//     "statusId": 1,
//     "userId": 3
// }]
// }


POST http://localhost:3000/api/worksheet/create-harvest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
   "worksheetId": 13,
    "count": 30,
    "unitId": 2, // 1 - Tins, 2- Frozen Cups, 3 - Millions
    "measuredBy": 1,
    "restockCount": 10,
    "restockUnitId": 3,
    "statusId": 4
}

POST http://localhost:3000/api/worksheet/get-harvests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "unitId": 2,
    "statusIds": ["A", "P"]
}

POST http://localhost:3000/api/worksheet/create-multiple-harvest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
  "harvests": [{
    "worksheetId": 22,
    "count": 70,
    "countInStock": 70,
    "unitId": 3,
    "measuredBy": 1,
    "restockCount": 20,
    "restockUnitId": 3,
    "statusId": 4
  }]
}

POST http://localhost:3000/api/worksheet/get-transits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "days": 3
}


POST http://localhost:3000/api/worksheet/create-multiple-transit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJDb2RlIjoiR01ILUFNUy0xNzExIiwiaWF0IjoxNzQ3NjI3MTU4LCJleHAiOjE3NTI4ODY3NTgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.-Y1_cLTugFGmNvvx9q75ZrnRLX4zmZN-osHrfjhcmRY

{
  "transits": [{
    "harvestId": 12,
    "unitSectorId": 1,
    "count": 20,
    "unitId": 1
  }, {
    "harvestId": 12,
    "unitSectorId": 2,
    "count": 20,
    "unitId": 1
  }],
  "harvestId": 12
}