{{
    // pre request scripts
    const date = new Date();
    exports.startDate = date.toString();
    exports.endDate = date.toString();
}}

GET http://localhost:3000/api/worksheet/get-worksheets
?limit=1
&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTA4MzcwOSwiZXhwIjoxNzQ1MDg3MzA5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.aN7s92E3uGU3m9SaBzWsJoqlgH25icgzXpx0zBIT0as


GET http://localhost:3000/api/worksheet/get-all-worksheets