GET http://localhost:3000/api/users
GET http://localhost:3000/api/users
?limit=5
&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJJZCI6IkdNSC1BTVMtMTYxMSIsImlhdCI6MTc0NDM3MDEwNSwiZXhwIjoxNzQ0MzczNzA1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.-CaVkR_Fmgs3kQX3hD-GgpAHKrqBi48Wpbij_U6P30E
