POST http://localhost:3000/users
Content-Type: application/json

{
    "userId": "GMH-AMS-1234",
    "firstName": "Prabakaran",
    "lastName": "A",
    "password": "test_98880",
    "mobileNumber": "9500010704",
    "role": "admin",
    "designation": "technician",
    "departmentUnit": "Unit-7",
    "dateOfJoining": "2016-09-18T17:34:02.666Z",
    "dateOfBirth": "2000-09-18T17:34:02.666Z",
    "address": "test address",
    "remarks": "test remarks"
}

POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJJZCI6IkdNSC1BTVMtMTExMiIsImlhdCI6MTc0NDI1ODQzMiwiZXhwIjoxNzQ0MjYyMDMyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.0hwyA718A-SYC7vHO5gNxqrEJS4O7LjC-zEChtw892U

{
    "userId": "GMH-AMS-1112",
    "firstName": "Devi",
    "lastName": "B",
    "password": "test_98880",
    "mobileNumber": "9500010704",
    "role": "admin",
    "designation": "technician",
    "departmentUnit": "Unit-7",
    "dateOfJoining": "2016-09-18T17:34:02.666Z",
    "dateOfBirth": "2000-09-18T17:34:02.666Z",
    "address": "test address",
    "remarks": "test remarks"
}


PATCH http://localhost:3000/users
Content-Type: application/json

{
    "name": "testcreate",
    "mobileNumber": "9500010704"
}