POST http://localhost:3000/api/users
Content-Type: application/json

{
    "userCode": "GMH-AMS-1",
    "firstName": "Bala",
    "lastName": "GMH",
    "password": "welcome123",
    "mobileNumber": "9500010704",
    "role": "admin",
    "designation": "Manager",
    "unitSectorId": 1,
    "dateOfJoining": "2016-09-18T17:34:02.666Z",
    "dateOfBirth": "2000-09-18T17:34:02.666Z",
    "address": "test address",
    "remarks": "test remarks"
}


PATCH http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
    "id": 9,
    "firstName": "AMS",
    "lastName": "Admin"
}

PATCH http://localhost:3000/api/users/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJDb2RlIjoiR01ILUFNUy0xNjExIiwiaWF0IjoxNzU0NjYwMDkyLCJleHAiOjE3NTk5MTk2OTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.SzLxeTYp_pC6bix3TtaFBJiGKUTfBzHOckTQyjWUCVU

{
    "userId": "GMH-AMS-1611",
    "newPassword": "test_16111"
}