POST http://localhost:3000/api/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImlhdCI6MTc0NDI5MTM3MiwiZXhwIjoxNzQ0Mjk0OTcyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.XwxPzvWOeosvVknEmsEL79yvXMR5CyoQ8snx4m1x6_E"
}