POST http://localhost:3000/api/master/unit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJJZCI6IkdNSC1BTVMtMTcxMSIsImlhdCI6MTc0NTIwODE0MCwiZXhwIjoxNzUyOTg0MTQwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rpUgvrO5iGls0A-_H1s2v5nir1cnJMXvgyFqqtxMnzY

{
  "description": "Bags",
  "value": "Bags"
}

POST http://localhost:3000/api/master/worksheet-unit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc1MzI4MjI4NSwiZXhwIjoxNzU4NTQxODg1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Vm-_HByVUxwulRAjrFR3bWoS8cL9xK8CYVjDtZGNPA8

{
  "value": "Unit B",
  "brand": "Brand A",
  "specs": "10kgs"
}


DELETE http://localhost:3000/api/master/worksheet-unit
?id=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJDb2RlIjoiR01ILUFNUy0xNzExIiwiaWF0IjoxNzU0MDI3ODMwLCJleHAiOjE3NTkyODc0MzAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.QGJa-d8BuWUH01hX8bND0-RmdBF1R64w_bWh31QGUpk
