export enum worksheetHistory {
  WORKSHEET_CREATED = 'WORKSHEET_CREATED',
  WORKSHEET_UPDATED = 'WORKSHEET_UPDATED',
  WORKSHEET_DELETED = 'WORKSHEET_DELETED',
  WORKSHEET_STATUS_UPDATED = 'WORKSHEET_STATUS_UPDATED',
  WORKSHEET_ASSIGNEE_UPDATED = 'WORKSHEET_ASSIGNEE_UPDATED',
}
